# Generated by Django 4.1.7 on 2023-03-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_user_user_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInRoom',
            new_name='Attendee',
        ),
        migrations.RenameModel(
            old_name='UserInRoomData',
            new_name='AttendeeData',
        ),
    ]
