# Generated by Django 4.1.7 on 2023-03-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_userinroom_attendee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeedata',
            name='direction',
            field=models.FloatField(),
        ),
    ]
